// plans/month2-project/farmap/src/views/login/index.vue
<script setup lang="ts">
	import { useUserStore } from '@/store';
	import { ref } from 'vue';

	const loginError = ref<boolean>(false);
	async function submitLoginForm(e: Event) {
		e.preventDefault();
		const form = e.target as HTMLFormElement;
		const formData = new FormData(form);

		let index = 0;
		for (const [key, val] of formData) {
			if (key === 'username' && val === 'admin') {
				index++;
			} else if (key === 'password' && val === '123') {
				index++;
			}
		}
		// try {
		// 	const res = await fetch(url, {
		// 		method: 'POST',
		// 		body: formData,
		// 	});
		// } catch (err) {
		// 	console.log(`[ERROR]: login failed with: ${err}`);
		// }
		if (index === 2) {
			const userStore = useUserStore();
			userStore.login({ name: 'mimi', token: '123123adf', role: 'admin' });
		} else {
			loginError.value = true;
		}
	}
</script>

<template>
	<div>login</div>
	<form @submit="submitLoginForm">
		<div>
			<label for="username">username</label>
			<input type="text" name="username" id="username" />
		</div>
		<div>
			<label for="password">password</label>
			<input type="text" name="password" id="password" />
		</div>
		<button>LOGIN</button>
	</form>
	<div v-if="loginError">username or password error</div>
</template>

// plans/month2-project/farmap_react/src/views/login/index.tsx
import { FormEvent, useState } from 'react';
import styles from './index.module.css';
import store, { login } from '@/store';

// logout
// store.dispatch(login({ token: '', username: '', role: '' }));
function Login() {
	const [loginError, setLogginError] = useState(false);
	const handleLogin = async (event: FormEvent) => {
		// FIXME: how to restrict the parameter of <store.dispatch>?
		event.preventDefault();
		// TODO: connect to backend
		const formData = new FormData(event.target as HTMLFormElement);
		const username = formData.get('username');
		const password = formData.get('password');
		if (username === 'admin' && password === '123') {
			store.dispatch(
				login({ token: '123123', username: 'admin1', role: 'admin' })
			);
		} else {
			setLogginError(true);
			setTimeout(() => {
				setLogginError(false);
			}, 3000);
		}
		// TODO: connetc to backend
	};

	return (
		<>
			<form onSubmit={handleLogin}>
				<div className="form-username">
					<label htmlFor="form-username__input">username</label>
					<input
						type="text"
						id="form-username__input"
						name="username"
						required
					/>
				</div>
				<div className="form-password">
					<label htmlFor="form-password__input">password</label>
					<input
						type="password"
						id="form-password__input"
						name="password"
						required
					/>
				</div>
				<button type="submit">login</button>
			</form>
			{loginError ? (
				<div className={styles['error-tip']}>
					username or passowrd not correct
				</div>
			) : null}
		</>
	);
}

export default Login;
