// plans/month2-project/farmap/src/layout/Layout.vue
<script setup lang="ts">
	import { baseUrl } from '@/constants';
	import { routes } from '@/router/routes';
	import type { RouteRecordRaw } from 'vue-router';

	interface Link {
		title: string;
		name: string;
		icon: string;
	}
	const mainLink: RouteRecordRaw[] = routes.filter((route) => route.name === 'main');
	const links: Link[] = mainLink[0].children!.map((route) => ({
		title: route.meta?.title as string,
		icon: route.meta?.icon as string,
		name: route.name as string,
	}));
</script>

<template>
	<div class="container">
		<nav class="sidebar">
			<div class="title">
				<img :src="`${baseUrl}/icons/logo.png`" alt="logo" />
				<div>智慧农业farmap</div>
			</div>
			<div class="links">
				<RouterLink class="link" v-for="(link, idx) in links" :key="idx" :to="link.name">
					<i :class="`ri-${link.icon}-line`"></i>
					<span>{{ link.title }}</span>
				</RouterLink>
				<div class="link logout">
					<i class="ri-logout-box-line"></i>
					<span>退出</span>
				</div>
			</div>
		</nav>
		<RouterView />
	</div>
</template>

<style scoped>
	.container {
		display: flex;
	}

	.sidebar {
		height: 100vh;
		background-color: azure;
	}

	.title {
		display: flex;
		align-items: center;
	}

	.title > img {
		width: 40px;
	}

	.links {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: start;
		height: calc(100% - 50px);
	}

	.logout {
		margin-top: auto;
	}
</style>

// plans/month2-project/farmap_react/src/layout/index.tsx
import styles from './index.module.css';
import { NavLink, Outlet } from 'react-router';
import { routes } from '@/router/routes';
import store, { logout } from '@/store';
import { baseUrl } from '@/constants';

function Layout() {
	const handleLogout = () => {
		store.dispatch(logout());
	};

	return (
		<>
			<div className={styles.container}>
				<nav className={styles.nav}>
					<div>
						<div className={styles.logo}>
							<img width="35" src={`${baseUrl}/icons/logo.png`} alt="logo" />
							<span>智慧农业FarMap</span>
						</div>
						{routes.map((route, index) => (
							<div className={styles['nav__single']} key={index}>
								<NavLink
									className={({ isActive }) =>
										isActive
											? `${styles.navlink} ${styles.active}`
											: styles.navlink
									}
									to={route.path}
									end>
									<i className={`ri-${route.icon}-fill`}></i>
									{route.name}
								</NavLink>
							</div>
						))}
					</div>
					<div className={styles['nav__single']}>
						<div
							className={`${styles.navlink} ${styles.logout}`}
							onClick={handleLogout}>
							<i className="ri-logout-box-r-line"></i>
							退出登录
						</div>
					</div>
				</nav>
				<Outlet />
			</div>
		</>
	);
}

export default Layout;
